"""rename department

Revision ID: ed303d66244a
Revises: c8f2e011d883
Create Date: 2024-11-19 08:58:12.040225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed303d66244a'
down_revision = 'c8f2e011d883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.rename_table('departments', 'department')
    # ### end Alembic commands ###
